create_config_files( ...
    'experiment_name', 'steph_90_02_tree', ...
    'email_for_notifications', '1live.life.queen.size1@gmail.com', ...
    'yeti_user', 'et2495', ...
    'structure_type', 'tree', ...
    'p_lambda_splits', 20, ...
    'p_lambdas_per_split', 1, ...
    'p_lambda_min', 1e+01, ...
			 'p_lambda_max', 1e+07);
