create_config_files( ...
    'experiment_name', 'steph_90_02_loopy', ...
    'email_for_notifications', '1live.life.queen.size1@gmail.com', ...
    'yeti_user', 'et2495', ...
    'compute_true_logZ', false, ...
    'reweight_denominator', 'mean_degree', ...
    's_lambda_splits', 6, ...
    's_lambdas_per_split', 1, ...
    's_lambda_min', 2e-03, ...
    's_lambda_max', 5e-01, ...
    'density_splits', 1, ...
    'densities_per_split', 4, ...
    'density_min', 0.01, ...
    'density_max', 0.04, ...
    'p_lambda_splits', 5, ...
    'p_lambdas_per_split', 1, ...
    'p_lambda_min', 1e+01, ...
			 'p_lambda_max', 1e+04);
